package com.clubflow.user;

/** Fine-grained capabilities. Roles are mapped to sets of these (see DefaultRolePermissions). */
public enum Permission {
    TASK_CREATE, TASK_ASSIGN, TASK_UPDATE, TASK_DELETE, TASK_APPROVE,
    TASK_VIEW_ALL, TASK_VIEW_ASSIGNED, TASK_UPDATE_ASSIGNED, TASK_SUBMIT,
    USER_VIEW, USER_CREATE, USER_UPDATE, USER_DELETE, USER_ROLE_UPDATE,
    EVENT_VIEW, EVENT_CREATE, EVENT_UPDATE, EVENT_DELETE,
    ANNOUNCEMENT_CREATE, TEMPLATE_MANAGE, DEPARTMENT_MANAGE,
    CLUB_UPDATE, CLUB_MANAGE,
    REPORT_VIEW, AUDIT_VIEW, SYSTEM_CONFIG
}
