package com.clubflow.notification;

public enum NotificationType {
    TASK_ASSIGNED, TASK_UPDATED, TASK_DEADLINE_CHANGED, TASK_REMINDER, TASK_OVERDUE,
    TASK_SUBMITTED, TASK_APPROVED, TASK_REJECTED, TASK_CANCELLED, TASK_COMMENT,
    EVENT_VOLUNTEER, ANNOUNCEMENT, SYSTEM
}
